# Generated by Django 2.1.7 on 2019-03-20 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20190319_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user_fav',
            new_name='favorite',
        ),
        migrations.AddField(
            model_name='post',
            name='fav_by',
            field=models.ManyToManyField(through='core.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
