# Generated by Django 2.1.7 on 2019-03-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_fav_by'),
        ('core', '0005_auto_20190320_1905'),
    ]

    operations = [
    ]
