# Generated by Django 2.1.7 on 2019-03-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_comment_comment_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_time']},
        ),
    ]
